finalize
20210502-FE/YakovlevaEleonora_UGMONK pull request #1
Opened 2021-06-14 09:31 UTC by ElyaYak

2021-07-04 15:08 UTC, JuliaSavych requested changes
Перевір ще раз верстку
деякі елементи зроблені дуже неправильно, також все зроблено не по БЕМу

2021-07-04 15:08 UTC, jules-js commented on .gitignore
> +
.vscode/

2021-07-04 15:08 UTC, jules-js commented on index.html
> +	<section class="banner_middle">
.banner-middle

2021-07-04 15:08 UTC, jules-js commented on index.html
> +		<div class="banner_middle_content">
.banner-middle__content

2021-07-04 15:08 UTC, jules-js commented on index.html
> +			<div class="banner_middle_content_text">
.banner-middle__text

2021-07-04 15:08 UTC, jules-js commented on index.html
> +			<div class="banner_middle_content_picture">
для чого цей порожній блок?

2021-07-04 15:08 UTC, jules-js commented on index.html
> +	<section class="main_menu">
це не меню

2021-07-04 15:08 UTC, jules-js commented on index.html
> +			<div class="main_menu_slogan">
.main-menu__slogan

2021-07-04 15:08 UTC, jules-js commented on index.html
> +	<section class="main_menu">
а якщо вже так, то .main-menu

2021-07-04 15:08 UTC, jules-js commented on index.html
> +			<div class="main_menu_content">
.main-menu__content

2021-07-04 15:08 UTC, jules-js commented on index.html
> +				<div class="main_menu_content_image">
.main-menu__content-image

2021-07-04 15:08 UTC, jules-js commented on index.html
> +						<div class="link_wrapper">
.link-wrapper

2021-07-04 15:08 UTC, jules-js commented on index.html
> +				<div class="main_menu_content_image_big">
.main-menu__content-image.main-menu__content-image_big

2021-07-04 15:08 UTC, jules-js commented on index.html
> +	<section class="banner_last">
.banner-bottom

2021-07-04 15:08 UTC, jules-js commented on index.html
> +		<div class="banner_last_content">
.banner-bottom__content

2021-07-04 15:08 UTC, jules-js commented on index.html
> +			<div class="banner_last_content_text">
.banner-bottom__text

2021-07-04 15:08 UTC, jules-js commented on index.html
> +				<h4 class="banner_last_content_text_title">Gathers</h4>
.banner-bottom__title

2021-07-04 15:08 UTC, jules-js commented on index.html
> +			<div class="banner_last_content_picture">
.banner-bottom__image

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +			<div class="banner_last_content_picture">
чому він порожній?

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +	<section class="banner_info">
.banner-info

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +		<div class="banner_info_content">
.banner-info__content

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +			<div class="banner_info_content_text">
.banner-info__text

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +		<div class="footer__container_left">
.footer__container.footer__container_left

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +			<ul>
.footer__list

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +				<li class="footer__container_left-item"><a href="#">Customer Service</a></li>
.footer__list-item

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +
remove empty line

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +		<div class="footer__container_center">
.footer__container.footer__container_center

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +		<div class="footer__container_right">
.footer__container.footer__container_right

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +		<div class="footer__container_right_icons">
.footer__socials

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +	<section class="banner_last">
чому всередині немає .wrapper?

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +	<section class="completed_menu">
.contact-us

2021-07-04 15:08 UTC, JuliaSavych commented on css/style.css
> +    padding: 0 604px;
для чого тут падінг?

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +	<section class="footer">
<footer>

2021-07-04 15:08 UTC, JuliaSavych commented on index.html
> +	<section class="footer">
![Screenshot from 2021-07-04 18-06-27](https://user-images.githubusercontent.com/19241160/124390062-a5652e00-dcf2-11eb-9141-f9a6e6b7f95c.png)

2021-07-06 11:55 UTC, EleonoraPavlova commented on .gitignore
> +
добавлю

2021-07-06 11:56 UTC, EleonoraPavlova commented on index.html
> +	<section class="banner_middle">
поняла

2021-07-06 11:57 UTC, EleonoraPavlova commented on index.html
> +	<section class="main_menu">
понятно

2021-07-06 11:59 UTC, EleonoraPavlova commented on index.html
> +			<div class="main_menu_slogan">
я помню на занятиях мы использовали _
одно нижнее подчеркивание не поняла где его применять

2021-07-06 12:03 UTC, EleonoraPavlova commented on index.html
> +			<div class="banner_last_content_picture">
кажется там картинка в css

2021-07-06 12:04 UTC, EleonoraPavlova commented on index.html
> +
ok

2021-07-06 12:05 UTC, EleonoraPavlova commented on index.html
> +	<section class="banner_last">
я думала он там не нужен

2021-07-06 12:08 UTC, EleonoraPavlova commented on css/style.css
> +    padding: 0 604px;
потому что у меня информация посередине улетает влево

2021-07-06 12:10 UTC, EleonoraPavlova commented on index.html
> +	<section class="footer">
почему поехало... нормально было.... разберусь

2021-07-06 12:12 UTC, EleonoraPavlova commented on css/style.css
> +    padding: 0 604px;
<img width="744" alt="Снимок экрана 2021-07-06 в 15 10 30" src="https://user-images.githubusercontent.com/82901679/124597770-89859780-de6c-11eb-83c3-19b3da3790f0.png">

2021-07-06 12:13 UTC, EleonoraPavlova commented on css/style.css
> +    padding: 0 604px;
<img width="1680" alt="Снимок экрана 2021-07-06 в 15 12 33" src="https://user-images.githubusercontent.com/82901679/124597850-a0c48500-de6c-11eb-8b2f-b39c17711af9.png">

2021-07-06 13:16 UTC, EleonoraPavlova commented on index.html
> +			<div class="banner_middle_content_picture">
<img width="607" alt="Снимок экрана 2021-07-06 в 16 16 23" src="https://user-images.githubusercontent.com/82901679/124606410-893dca00-de75-11eb-9502-c16afe5054fb.png">

2021-07-06 13:18 UTC, EleonoraPavlova commented on index.html
> +			<div class="banner_middle_content_picture">
тут картинка, я по другому не знаю и не нашла варианта. Только сделать пустой див и дать ему background

2021-07-06 13:39 UTC, EleonoraPavlova commented on index.html
> +				<div class="main_menu_content_image_big">
тут я вообще испугалась!
<img width="545" alt="Снимок экрана 2021-07-06 в 16 39 24" src="https://user-images.githubusercontent.com/82901679/124609907-bb9cf680-de78-11eb-8970-42e2f7e3b7e0.png">

2021-07-06 13:40 UTC, EleonoraPavlova commented on index.html
> +				<div class="main_menu_content_image_big">
такое длинное название! уместно ли это?

2021-07-07 12:28 UTC, EleonoraPavlova commented on index.html
> +	<section class="banner_last">
незнаю, без него тоже неплохо вроде)

2021-07-07 12:50 UTC, EleonoraPavlova commented on css/style.css
> +    padding: 0 604px;
убрала это

2021-10-11 12:13 UTC, merged